# Generated by Django 4.1.2 on 2022-10-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
