# Generated by Django 4.1.1 on 2022-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_category_options_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
