# Generated by Django 4.1.2 on 2022-10-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_remove_product_type_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField(default=0, verbose_name='Сумма скидки')),
                ('last_price', models.IntegerField(default=0, verbose_name='Старая цена')),
                ('new_price', models.IntegerField(default=0, verbose_name='Новая цена')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.product', verbose_name='Скидка')),
            ],
        ),
    ]
