# Generated by Django 4.1.2 on 2022-10-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
