# Generated by Django 4.1.2 on 2022-10-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_cart_productsincart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='productsincart',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
