# Generated by Django 4.1.2 on 2022-10-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_alter_cart_options_alter_productsincart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='count_in_order', to='magazine.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество товара в заказе'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductsInCart',
        ),
    ]
