# Generated by Django 4.1.2 on 2022-10-19 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0012_cart_product_cart_quantity_delete_productsincart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ProductsInCart',
        ),
    ]
