# Generated by Django 4.1.2 on 2022-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
