# Generated by Django 4.1.2 on 2022-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('sale',), 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='last_price',
            field=models.FloatField(default=0, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='new_price',
            field=models.FloatField(default=0, verbose_name='Новая цена'),
        ),
    ]
