# Generated by Django 4.1.2 on 2022-10-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_alter_productsincart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsincart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.cart', verbose_name='Заказ'),
        ),
    ]
