# Generated by Django 4.1.3 on 2022-12-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_cart_product_cart_quantity_delete_productsincart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
